name: Daily cron job
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request POST \
          --url 'https://my-coin-app.vercel.app/api/cronJob/history' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_KEY }}'